### ISSUE TITLE
Deprecate wget

### ISSUE THREAD

**Issue by UnrealQuester** [johanek/johanek-redmine#26]
Handling wget requires serveral special cases and does not work properly when trying to upgrade to a new version. Serveral Exec commands rely on creating files to check if they already ran. This fails when downloading a new version because we create a new directory. In addition, the user still has to copy over his attachments and other changes he made to redmine.
I am in favour of printing a deprecation warning and removing wget in the next major version.

**Comment by johanek** [comment]
I think this is a good idea as it will simplify the module.
