### ISSUE TITLE
Clean up requirements section of README

### ISSUE THREAD

**Issue by johanek** [johanek/johanek-redmine#29]
This is difficult to parse, particularly on the forge: https://forge.puppetlabs.com/johanek/redmine/readme

**Comment by UnrealQuester** [comment]
I think we can remove that section entirely. Most users won't care what packeges/gems/modules are installed. These are not even requirements at this point, just a list of things we fo for the user anyway.
Vote in favour of removing this paragraph.

**Comment by johanek** [comment]
There are puppet module dependencies, these should be kept. I agree that the system packages can be dropped.
