### ISSUE TITLE
Add support for installing Redmine in a subdirectory of the main webhost

### ISSUE THREAD

**Issue by zipkid** [johanek/johanek-redmine#32]
This needs just 2 small changes in the config files (config/environment.rb and the apache::vhost config).
It does however mean that the 'main' vhost may be managed somewhere else.... so there needs to be thought how to handle this best.

Bare code changes:

in redmine config/environment.rb, add as last line

    Redmine::Utils::relative_url_root = "/<Redmine Subdirectory>" 

in the vhost config change the following

    -    custom_fragment => 'RailsBaseURI /',
    +    custom_fragment => "  PassengerAppRoot ${redmine::webroot}\n  RailsBaseURI /<Redmine Subdirectory>",

It would also mean you may want to set webroot to another directory so we'd need to add a 'directories' parameter to the vhost config

What are your thoughts on this?

**Comment by UnrealQuester** [comment]
We could add a subdirectory parameter for the redmine class and then set the relative_url_root accordingly. The user would have to define the vhost in this case. The required custom_fragment and directories configuration can be in the README so that the user just has to copy it to their own vhost.

**Comment by zipkid** [comment]
Sounds like a good solution.
I hope to find time in the next few days to start on implementing this.

**Comment by johanek** [comment]
Hey,

How will this affect the log rotation config we deploy?

**Comment by UnrealQuester** [comment]
The only logs we have to rotate are in redmine::install_dir/logs. The template for logrotate currently uses redmine::webroot, which is just a symlink to redmine::install_dir. This should be changed to use redmine::install_dir. Which it should be using in the first place.
