### ISSUE TITLE
error while installing on centos 7

### ISSUE THREAD

**Issue by anilgautam** [johanek/johanek-redmine#34]
Hi, I tried using the module But got this error 

==> default: Error: ruby script/rails server webrick -e development returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Redmine::Run/Exec[run_redmine]/returns: change from notrun to 0 failed: ruby script/rails server webrick -e development returned 1 instead of one of [0]
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install libmysql-ruby' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package libmysql-ruby
==> default: 
==> default: Error: /Stage[main]/Redmine::Install/Package[libmysql-ruby]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install libmysql-ruby' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package libmysql-ruby
==> default: 
==> default: Notice: /Stage[main]/Redmine::Install/Exec[bundle_redmine]: Dependency Package[libmysql-ruby] has failures: true
==> default: Warning: /Stage[main]/Redmine::Install/Exec[bundle_redmine]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Redmine::Install/Exec[bundle_update]: Dependency Package[libmysql-ruby] has failures: true
==> default: Warning: /Stage[main]/Redmine::Install/Exec[bundle_update]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Redmine::Rake/Exec[session_store]: Dependency Package[libmysql-ruby] has failures: true
==> default: Warning: /Stage[main]/Redmine::Rake/Exec[session_store]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Redmine::Rake/Exec[rails_migrations]: Dependency Package[libmysql-ruby] has failures: true
==> default: Warning: /Stage[main]/Redmine::Rake/Exec[rails_migrations]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Redmine::Rake/Exec[seed_db]: Dependency Package[libmysql-ruby] has failures: true
==> default: Warning: /Stage[main]/Redmine::Rake/Exec[seed_db]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apache::Service/Service[httpd]: Dependency Package[libmysql-ruby] has failures: true
==> default: Warning: /Stage[main]/Apache::Service/Service[httpd]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 34.30 seconds

Any Idea how to fix this?

**Comment by johanek** [comment]
Hello,

This is happening because a dependency, libmysql-ruby, can't be installed.

Are you sure this is CentOS 7? The output mentions apt-get so it looks like Ubuntu. Do know what release of Ubuntu you're running?

**Comment by anilgautam** [comment]
Yes, I am using CentOS 7 
in my Vagrantfile
  config.vm.box = "chef/centos-7.0"

also how can I install libmysql-ruby on centOS-7.0 using your plugin?

**Comment by johanek** [comment]
Could I get a copy of your Vagrantfile so I can try to debug this please?

**Comment by anilgautam** [comment]
Here is my Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "chef/centos-7.0"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3000, host: 8081


  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "ubuntu/trusty64"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "a/modules"
  end
end

**Comment by johanek** [comment]
I've had go deploying this on CentOS 7.0 using the Vagrantfile / basebox your shared with me.

Unfortunately the puppetlabs-apache apache::mod::passenger doesn't support CentOS 7.0  because there's no mod_passenger package available for the platform yet: https://forge.puppetlabs.com/puppetlabs/apache#rhelcentos-7

So this is only going to work on CentOS 7.0 if you configure passenger yourself somehow.

However, if I don't include that class, everything else in the puppet run completes successfully. (If you specify version 2.5.2 and ignore the starting httpd error due to lack of passenger module)

From the error output you sent, it really looks like you're provisioning on an Ubuntu machine. Are you certain you don't have a configured box from a previous vagrant session lying around and you're using that by mistake?

Could you login to the box and check, by running `vagrant ssh` then `facter` please?

Also, the module doesn't have any dependency on libmysql-ruby - this is providing mysql support for ruby on Ubuntu. We use bundler to install the required gems, rather than using system packages. The module also doesn't include a class `Redmine::Run` that you mentioned in your error. Do you have some other modules or manifests that are conflicting with this module maybe?

**Comment by anilgautam** [comment]
Hi, johanek I tried installing it on CentOS 6.5 CentOS7 and Ubuntu 14.04. But I am not able to use it.
Can you let me know
how can I install CentOS 6.5. because in centOS 6.5. I was not able to install puppet on client machine. When I tried using yum install puppet. It says system.d is required and system.d is not avaliable for CentOS 6 versions. 

So right now I got stuck using all 3 approaches.

**Comment by johanek** [comment]
I managed to do the following to get a working install:

- Create a directory for the vagrant config
- Added the following Vagrantfile:
```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
  end
end
```
- Created manifests/default.pp
```
class { 'apache': }
class { 'apache::mod::passenger': }
class { '::mysql::server': }
class { 'redmine': }
```
- Installed the necessary puppet modules by running:
```
puppet module --modulepath modules/ install johanek-redmine
```
- Started machine with `vagrant up`
- Added 'redmine' alias to 127.0.0.1 in /etc/hosts on the host machine
```
127.0.0.1       localhost redmine
```
- Connected to redmine instance at http://redmine:8000

I hope this helps

**Comment by anilgautam** [comment]
Thankyou so much. It worked :+1:

**Comment by johanek** [comment]
Great news! Thanks for your problem reports - this has highlighted that the setup process on CentOS isn't working very well, so I'm going to spend some time trying to improve that.
