### ISSUE TITLE
show Index of /html/redmine/public after installation on Ubuntu 64

### ISSUE THREAD

**Issue by anilgautam** [johanek/johanek-redmine#35]
Hi, I tried to install redmine and after installation when I open the redmine it shows me list of files.
This is my redmine.conf filee located in /etc/apache2/sites-available/

<VirtualHost *:80>
  ServerName redmine

  ## Vhost docroot
  DocumentRoot "/var/www/html/redmine/public"

  ## Directories, there should at least be a declaration for /var/www/html/redmine/public

  <Directory "/var/www/html/redmine/public">
    Options Indexes FollowSymlinks ExecCGI
    AllowOverride None
    Require all granted
  </Directory>

  ## Logging
  ErrorLog "/var/log/apache2/redmine_error.log"
  ServerSignature Off
  CustomLog "/var/log/apache2/redmine_access.log" combined

  ## Server aliases
  ServerAlias redmine

  ## Custom fragment
RailsBaseURI /
</VirtualHost>

**Comment by johanek** [comment]
Hi there,

By default, the module configures an apache vhost for the servername `redmine` - you need to be connecting to that host name for redmine to work. Ubuntu, by default, enables directory indexes so if you connect to the system with any other hostname, you'll just get the directory listing of the system web root.

If you're using vagrant and port forwarding, then connecting to `http://localhost:8080` means you'll hit that system web root directory listing.

You can configure the hostname(s) that are used to serve up redmine with the `vhost_servername` and `vhost_aliases` parameters. If you wanted redmine to be available under localhost when running from vagrant, you could configure the vhost like:

```
class { 'redmine':
  vhost_servername => 'localhost'
}
```

Of course, that wouldn't be how you would want to deploy it in a production setting.

Alternatively, you could update /etc/hosts on your system so 'redmine' resolves to localhost

Let me know if you need any help with this!

**Comment by anilgautam** [comment]
Hi, I changed default.pp file to 

class { 'apache': }
class { 'apache::mod::passenger': }
class { '::mysql::server': }
include git
class { '::mysql::client': }
class { 'redmine':
vhost_servername => 'localhost',
vhost_aliases => 'localhost'
 }
and then tried  vagrant reload --provision but it does not work it still same.

Also 
I did not get this 'Alternatively, you could update /etc/hosts on your system so 'redmine' resolves to localhost"

there is no /etc/hosts in ubuntu.

**Comment by johanek** [comment]
Hey - please see #34 which has full instructions on getting this working on Ubuntu 14.04
