### ISSUE TITLE
rmagick and ruby 1.8

### ISSUE THREAD

**Issue by johanek** [johanek/johanek-redmine#43]
The `bundle install` step on Ubuntu 12.04 and CentOS 6 fails. This is because the latest version of rmagick doesn't install with ruby 1.8

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.8 extconf.rb 
extconf.rb:153: undefined (?...) sequence: /^Version: ImageMagick\s+(?<Version>\d+\.\d+\.\d+\-\d+)\s+(?<Unknown>\S+)\s+(?<Arch>\S+)\s+(?<Date>\S+)/
```

Looks like the latest rmagick 2.13.4 says it supports ruby 1.8, but uses 1.9+ syntax in this regex? It looks like this has been fixed in master, but hasn't been released: https://github.com/gemhome/rmagick/blob/master/ext/RMagick/extconf.rb#L79

rmagick 2.13.3 installs fine. The redmine Gemfile only specifies rmagick >= 2.0.0

**Comment by UnrealQuester** [comment]
What redmine version were you using?

**Comment by johanek** [comment]
The default version - 2.2.3

**Comment by UnrealQuester** [comment]
This seems to be a bug/oversight in redmine that has been fixed in 2.6.1. I do not think we can anything here. Checking compatibility for every possible distribution, ruby version, and redmine version is not possible. This could perhaps be somewhat avoided by letting the user pick the version he wants. The user could then check redmine.org for the latest version which hopefully has the least problems with major distros.

**Comment by johanek** [comment]
Sure, this is a problem with upstream components that you would have if you use our module or not.

But, in handling #34 earlier this week it became clear to me that the new user experience for using the module is not awesome. I'd like to make it so that if you follow the 'example usage' documentation for a platform we claim to support, then this should work reliably. Many of the issues I've been creating in the past couple of days are related to this idea. (We should probably track that in a single issue somehow)

So how do we handle this problem to make the user experience better? As you've identified, the best fix is to update the redmine Gemfile to set the rmagick dependency better, but that's an upstream issue - we shouldn't be trying to manage the content of this file at all. Since redmine 2.6.1 fixes the Gemfile, perhaps we can solve this via #38 and set a more appropriate default version. Ideally this would be the same across all distros & releases, but if that's not possible then we should set an appropriate default per distro & release.

More broadly, I'm working on some automated tests that the module installs successfully on supported releases to allow us to identify problems more easily in future.

**Comment by johanek** [comment]
Ubuntu 12.04 can't run a new enough redmine version that fixes this. If we don't end up managing passenger as per #37 then we could work around this by manually installing a working gem before running `bundle install`

**Comment by UnrealQuester** [comment]
I am no expert on gem and bundler. If we add a `gem install rmagick 2.13.3` in certain edge cases (ruby version < 1.9 and redmine version < 2.6.1) before bundle install, would that work? I am not sure how multiple versions of the same package are handled in case the user already has rmagick installed.

**Comment by johanek** [comment]
If rmagick was already installed, bundler won't install another version as the dependency is already satisfied. Let's do this

**Comment by johanek** [comment]
I was wrong, bundler always tries to install the latest version: https://github.com/bundler/bundler/issues/1964

The rmagick bug is being tracked here: https://github.com/gemhome/rmagick/issues/171

Looks like everything is in place to create a new release so I've pinged them to see if they can do so

**Comment by UnrealQuester** [comment]
Okay. It looks like the only thing we can do is wait.

**Comment by johanek** [comment]
rmagick 2.14.0 was released, which resolves this issue.
