### ISSUE TITLE
drop support for Ubuntu 10.04

### ISSUE THREAD

**Issue by johanek** [johanek/johanek-redmine#49]
Has a couple of problems that I've identified so far...

git package name is git-core rather than git, so we need to change $provider_package in params.pp to fix this (simple but annoying)

version of rubygems installed is too old for required bundler, even when installing the default version of redmine:

```
Error: Execution of '/usr/bin/gem install --no-rdoc --no-ri bundler' returned 1: ERROR:  Error installing bundler:
bundler requires RubyGems version >= 1.3.6
```

It's just too old, time to drop it.

**Comment by UnrealQuester** [comment]
The redmine wiki states that the official packages for redmine in ubuntu 10.04 are at 0.9.x. In favour.
