### ISSUE TITLE
Replace Apache with Nginx + Unicorn

### ISSUE THREAD

**Issue by sammcj** [johanek/johanek-redmine#61]
It would be great if you could replace or add the option to use Nginx + Unicorn rather than Apache Passenger.

Nginx + Unicorn as a combination is considerably faster and generally uses far less resources.

This would also help resolve #37

**Comment by johanek** [comment]
Hi

I don't think there are any plans to support nginx+unicorn I'm afraid. I'm not available to work on this project anymore.

There was once a PR, never merged, to make apache optional so you could use nginx instead: #16 

I saved that branch here: https://github.com/johanek/johanek-redmine/compare/feature/clouddevelops-extended-features
